### ISSUE TITLE
Webpack React Example

### ISSUE THREAD

**Issue by allencoded** [Vheissu/aurelia-react-example#3]
Thanks for all your hard work in making React work in Aurelia. I noticed though your example doesn't support webpack. I took the liberty of adding your example into the aurelia-webpack-skeleton and changing their webpack config to transpile react files.

You can find my work at:
[Aurelia-React-Skeleton](https://github.com/allencoded/aurelia-react-skeleton/)

Also the wiki I drew up at:
[Aurelia-React-Skeleton-Wiki](https://github.com/allencoded/aurelia-react-skeleton/wiki/Aurelia-with-React-using-Webpack)

**Comment by Xceno** [comment]
Hey folks!
@allencoded I just stumbled across this issue and your work which finally got me set up in the right direction, so thanks!

So I was finally able to take the official `skeleton-typescript-webpack` and add react:
[aurelia-skeleton-typescript-react-webpack](https://github.com/Xceno/aurelia-skeleton-typescript-react-webpack)
